# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "23419f65466bf88a39cb842cf3b570f4cc7ada4b"

[[deps.AdventOfCode2025]]
path = "."
uuid = "f75e17d3-f987-4e71-a56d-f956b91f4668"
version = "0.1.0"
