# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "5fae00dddff305e0b4865faf525c3f24df38e1be"

[[deps.AdventOfCode2025]]
path = "."
uuid = "f75e17d3-f987-4e71-a56d-f956b91f4668"
version = "0.1.0"

[[deps.Utils]]
path = "src/advent_of_code_2025/Utils"
uuid = "5a498afa-9db5-4669-9dba-79ab0ad7edfc"
version = "0.1.0"
