name = "AdventOfCode2025"
uuid = "f75e17d3-f987-4e71-a56d-f956b91f4668"
version = "0.1.0"
authors = ["Rory Schadler <48921090+roryschadler@users.noreply.github.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Utils = "5a498afa-9db5-4669-9dba-79ab0ad7edfc"

[sources]
Utils = {path = "src/advent_of_code_2025/utils"}

[compat]
Combinatorics = "1.0.3"
DataStructures = "0.19.3"
Graphs = "1.13.2"
LinearAlgebra = "1.12.0"
